// src/backend-interfaces/truth-dtos.ts

// This file defines the Data Transfer Objects (DTOs) that represent
// the structure of data exchanged between the frontend and backend,
// and how truths are stored persistently.

/**
 * Represents a relationship between two truths.
 */
export interface BackendTruthRelationshipDTO {
  targetTruthId: string;
  relationshipType: 'supersedes' | 'contradicts' | 'supports' | 'references';
  confidence: number; // Confidence in this specific relationship (0.0-1.0)
  notes?: string;
}

/**
 * Represents a complete Truth Ledger Entry as it would be stored in the backend
 * and transferred to/from the frontend.
 * This extends the frontend's `TruthLedgerEntry` but can include backend-specific fields
 * like a database's primary key (`_id` or `dbId`) if `id` is not the natural primary key.
 */
export interface BackendTruthLedgerEntryDTO {
  // Core identity - typically a UUID or database ID
  id: string; // Unique identifier for the truth

  // Metadata
  timestamp: string; // ISO string creation timestamp

  // Content and status of the truth
  content: string; // The raw TypeScript confidence block string
  status: 'proposed' | 'accepted' | 'rejected' | 'superseded' | 'challenged' | 're-accepted';
  confidence: number; // The system's calculated confidence in this truth (0.0-1.0)
  notes?: string; // General notes about the truth

  // Cryptographic immutability details
  contentHash: string; // SHA-256 hash of the truth's content for integrity verification
  previousHash: string; // Hash of the previous truth in the ledger chain (for blockchain-like integrity)

  // Doubt resolution specific metadata
  challengedBy?: string; // ID of the entity that challenged this truth
  challengeReason?: string; // Reason provided for the challenge
  challengeTimestamp?: string; // ISO string timestamp of when the truth was challenged

  resolvedBy?: string; // ID of the entity that resolved the challenge
  resolutionType?: 're-accepted' | 'rejected'; // Outcome of the challenge resolution
  resolutionNotes?: string; // Notes detailing the resolution decision
  resolutionTimestamp?: string; // ISO string timestamp of when the challenge was resolved

  // Relationships to other truths
  relationships: BackendTruthRelationshipDTO[];

  // --- Backend-specific fields (examples, might vary based on persistence layer) ---
  // createdAt: Date; // Database creation timestamp (could be different from 'timestamp')
  // updatedAt: Date; // Last update timestamp (for mutable metadata, not truth content)
  // version: number; // Optimistic locking or version tracking
  // _partitionKey?: string; // For distributed databases
}

/**
 * Interface for proposing a new truth to the backend.
 * This might be slightly different from the full DTO as some fields (like id, hash, status)
 * are generated by the backend.
 */
export interface ProposeTruthRequestDTO {
  content: string;
  initialRelationships?: Omit<BackendTruthRelationshipDTO, 'confidence'>[]; // Confidence may be assigned by backend
  // Potentially other metadata like 'authorId', 'sourceSystem'
}

/**
 * Interface for challenging a truth on the backend.
 */
export interface ChallengeTruthRequestDTO {
  challengerId: string;
  reason: string;
}

/**
 * Interface for resolving a challenged truth on the backend.
 */
export interface ResolveTruthRequestDTO {
  resolverId: string;
  resolutionType: 're-accepted' | 'rejected';
  resolutionNotes: string;
}

/**
 * Interface for adding a relationship to an existing truth.
 */
export interface AddRelationshipRequestDTO {
  targetTruthId: string;
  relationshipType: BackendTruthRelationshipDTO['relationshipType'];
  confidence: number;
  notes?: string;
}
