name: Kernel Heartbeat

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Generate status.json heartbeat
      run: |
        echo "{\"last_heartbeat\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > status.json
        echo "$(date -u) - Triggered" >> .force_trigger.txt

    - name: Commit and Push Heartbeat to Repo
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.email "ai@kernel.bot"
        git config --global user.name "AI Kernel"
        git checkout main || git checkout master
        git pull
        git add status.json .force_trigger.txt
        git commit -m "💓 Kernel heartbeat at $(date -u)" || echo "No changes to commit"
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
