name: Update AVOS PNG

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: true
        default: 'AVOS: Reflex update'
      base64_png:
        description: 'Base64-encoded runtime.afe.png'
        required: true

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Decode and Save PNG
      run: |
        echo "${{ github.event.inputs.base64_png }}" | base64 -d > runtime.afe.png

    - name: Commit and Push Changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "avos-agent"
        git config user.email "agent@avos.local"
        git add runtime.afe.png
        git commit -m "${{ github.event.inputs.message }}"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
